arb-dir: lib/core/l10n/raw_translations
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
untranslated-messages-file: untranslated.txt
output-dir: lib/core/l10n/generated_translations
